### ISSUE TITLE
Provide annotation in all templates

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-iec#3]
Need to annotate templates up to the standard of https://raw.githubusercontent.com/metanorma/mn-templates-iso/master/international-standard/document.adoc.

**Comment by manuelfuenmayor** [comment]
@ronaldtse , by "annotation" you mean comments (`:comment:`), right?

**Comment by ronaldtse** [comment]
Yes, thanks.

**Comment by manuelfuenmayor** [comment]
PR added in https://github.com/metanorma/mn-templates-iec/pull/10

**Comment by manuelfuenmayor** [comment]
Task is merged. Closing.
