### ISSUE TITLE
About the functionality of some attributes

### ISSUE THREAD

**Issue by manuelfuenmayor** [metanorma/mn-templates-iec#9]
Hello!
I was inserting some comments in a IEC template and found that several attributes seems to make no impact in the document. So, I have two questions please:

1. Do these following attributes make any difference in Metanorma: `sectnumlevels`,  `xrefstyle`, `appendix-caption`, `appendix-refsig`, `section-refsig`, `table-caption`, `example-caption`, `toc` ? (I tested them in a document and it seems they don't.)

2. What is `unchangeddate` attribute for? (I didn't find anything in the official documentation.)

These attributes are set in [iec-rice template](https://raw.githubusercontent.com/metanorma/mn-templates-iec/master/iec-rice/document.adoc)

Thanks!

**Comment by ronaldtse** [comment]
> Do these following attributes make any difference in Metanorma: sectnumlevels, xrefstyle, appendix-caption, appendix-refsig, section-refsig, table-caption, example-caption, toc ? (I tested them in a document and it seems they don't.)

I don't think these matter in Metanorma. We should remove all of these from all documents and templates.

> What is unchangeddate attribute for? (I didn't find anything in the official documentation.)

This is the date where the document is stated to have not changed since. I don't remember where it came from, @opoudjis probably knows?

**Comment by opoudjis** [comment]
>> Do these following attributes make any difference in Metanorma: sectnumlevels, xrefstyle, appendix-caption, appendix-refsig, section-refsig, table-caption, example-caption, toc ? (I tested them in a document and it seems they don't.)

> I don't think these matter in Metanorma. We should remove all of these from all documents and templates.

Correct: they are the native Asciidoctor to HTML mechanism of preserving captions, and at the very beginning, I kept them around because I wanted the option of us using native Asciidoctor HTML as well. I agree with Ronald, we don't need them any more.

https://www.relaton.com/specs/model/production/ does mention "unchanged", which is what unchangeddate corresponds to:

> Date a resource was reprinted, i.e. republished without any changes.

`:unchanged-date:` is also mentioned  on https://www.metanorma.com/author/ref/document-attributes/#timestamps

**Comment by manuelfuenmayor** [comment]
Thanks @opoudjis !

So, should I update `:unchangeddate:` to `:unchanged-date:` or it doesn't matter at all?

**Comment by opoudjis** [comment]
> So, should I update :unchangeddate: to :unchanged-date: or it doesn't matter at all?

Yes, the code recognises only the latter.
